// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/center.proto

package trace

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4acfdbf4d8b001b, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4acfdbf4d8b001b, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Packet struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4acfdbf4d8b001b, []int{2}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadResult struct {
	Size                 uint64   `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Checksum             []byte   `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResult) Reset()         { *m = UploadResult{} }
func (m *UploadResult) String() string { return proto.CompactTextString(m) }
func (*UploadResult) ProtoMessage()    {}
func (*UploadResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4acfdbf4d8b001b, []int{3}
}

func (m *UploadResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResult.Unmarshal(m, b)
}
func (m *UploadResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResult.Marshal(b, m, deterministic)
}
func (m *UploadResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResult.Merge(m, src)
}
func (m *UploadResult) XXX_Size() int {
	return xxx_messageInfo_UploadResult.Size(m)
}
func (m *UploadResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResult.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResult proto.InternalMessageInfo

func (m *UploadResult) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *UploadResult) GetChecksum() []byte {
	if m != nil {
		return m.Checksum
	}
	return nil
}

type Judgment struct {
	Team                 string   `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Score                float32  `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Judgment) Reset()         { *m = Judgment{} }
func (m *Judgment) String() string { return proto.CompactTextString(m) }
func (*Judgment) ProtoMessage()    {}
func (*Judgment) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4acfdbf4d8b001b, []int{4}
}

func (m *Judgment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Judgment.Unmarshal(m, b)
}
func (m *Judgment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Judgment.Marshal(b, m, deterministic)
}
func (m *Judgment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Judgment.Merge(m, src)
}
func (m *Judgment) XXX_Size() int {
	return xxx_messageInfo_Judgment.Size(m)
}
func (m *Judgment) XXX_DiscardUnknown() {
	xxx_messageInfo_Judgment.DiscardUnknown(m)
}

var xxx_messageInfo_Judgment proto.InternalMessageInfo

func (m *Judgment) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *Judgment) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "trace.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "trace.HelloResponse")
	proto.RegisterType((*Packet)(nil), "trace.Packet")
	proto.RegisterType((*UploadResult)(nil), "trace.UploadResult")
	proto.RegisterType((*Judgment)(nil), "trace.Judgment")
}

func init() {
	proto.RegisterFile("proto/center.proto", fileDescriptor_b4acfdbf4d8b001b)
}

var fileDescriptor_b4acfdbf4d8b001b = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x29, 0x01, 0xac, 0x13, 0x88, 0xc9, 0x48, 0x0c, 0xa9, 0x1e, 0xcc, 0x9e, 0xf0, 0x52,
	0x08, 0x6a, 0xbc, 0x79, 0x11, 0x13, 0xe3, 0x45, 0x53, 0xe2, 0x0f, 0x58, 0xca, 0x58, 0x0c, 0x6d,
	0xb7, 0x76, 0x77, 0x63, 0xf0, 0xe7, 0xfa, 0x4b, 0x4c, 0x67, 0x59, 0x03, 0xde, 0xe6, 0x4d, 0xdf,
	0xdb, 0xce, 0xfb, 0x00, 0xab, 0x5a, 0x19, 0x35, 0x49, 0xa9, 0x34, 0x54, 0xc7, 0x2c, 0xb0, 0x6b,
	0x6a, 0x99, 0x52, 0x74, 0x9e, 0x29, 0x95, 0xe5, 0x34, 0xe1, 0xe5, 0xd2, 0xbe, 0x4f, 0xa8, 0xa8,
	0xcc, 0xd6, 0x79, 0x84, 0x80, 0xfe, 0x13, 0xe5, 0xb9, 0x4a, 0xe8, 0xd3, 0x92, 0x36, 0x88, 0xd0,
	0x29, 0x65, 0x41, 0xa3, 0xe0, 0x32, 0x18, 0x1f, 0x27, 0x3c, 0x8b, 0x2b, 0x18, 0xec, 0x3c, 0xba,
	0x52, 0xa5, 0x26, 0x1c, 0xc1, 0x51, 0x41, 0x5a, 0xcb, 0xcc, 0xfb, 0xbc, 0x14, 0x17, 0xd0, 0x7b,
	0x95, 0xe9, 0x86, 0xf8, 0xa1, 0x95, 0x34, 0x92, 0x0d, 0xfd, 0x84, 0x67, 0x71, 0x0f, 0xfd, 0xb7,
	0x2a, 0x57, 0x72, 0x95, 0x90, 0xb6, 0x39, 0x7b, 0xf4, 0xc7, 0xb7, 0x7b, 0xa4, 0x93, 0xf0, 0x8c,
	0x11, 0x84, 0xe9, 0x9a, 0xd2, 0x8d, 0xb6, 0xc5, 0xa8, 0xcd, 0xd9, 0x3f, 0x2d, 0x6e, 0x20, 0x7c,
	0xb6, 0xab, 0xac, 0xa0, 0x92, 0xb3, 0x86, 0x64, 0xe1, 0x0f, 0x6d, 0x66, 0x1c, 0x42, 0x57, 0xa7,
	0xaa, 0x26, 0x0e, 0xb6, 0x13, 0x27, 0x66, 0x3f, 0x01, 0xc0, 0x5c, 0x1a, 0xf9, 0xc0, 0x6c, 0xf0,
	0x0e, 0xc2, 0x85, 0xdc, 0x72, 0x21, 0x3c, 0x8d, 0x19, 0x51, 0xbc, 0x8f, 0x20, 0x1a, 0x1e, 0x2e,
	0x5d, 0x67, 0xd1, 0xc2, 0x5b, 0x08, 0xe7, 0xea, 0xab, 0x6c, 0xee, 0xc7, 0xb3, 0xd8, 0x41, 0x8d,
	0x3d, 0xd4, 0xf8, 0xb1, 0x81, 0x1a, 0x0d, 0x76, 0x59, 0x07, 0x41, 0xb4, 0xa6, 0x01, 0x4e, 0xa1,
	0xe7, 0x4a, 0xe3, 0xe1, 0xc7, 0xc8, 0xff, 0x7c, 0x1f, 0x89, 0x68, 0x8d, 0x03, 0x9c, 0x41, 0xb8,
	0x58, 0x2b, 0x6b, 0x5e, 0xac, 0xc1, 0x93, 0x9d, 0xc9, 0xf7, 0x8e, 0xfe, 0x2f, 0x9a, 0xc4, 0x34,
	0x58, 0xf6, 0xf8, 0x90, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0xa5, 0x33, 0x3b, 0x08,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataCenterClient is the client API for DataCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataCenterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	Download(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (DataCenter_DownloadClient, error)
	Upload(ctx context.Context, opts ...grpc.CallOption) (DataCenter_UploadClient, error)
	ShoutOut(ctx context.Context, opts ...grpc.CallOption) (DataCenter_ShoutOutClient, error)
}

type dataCenterClient struct {
	cc grpc.ClientConnInterface
}

func NewDataCenterClient(cc grpc.ClientConnInterface) DataCenterClient {
	return &dataCenterClient{cc}
}

func (c *dataCenterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/trace.DataCenter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCenterClient) Download(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (DataCenter_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataCenter_serviceDesc.Streams[0], "/trace.DataCenter/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataCenterDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataCenter_DownloadClient interface {
	Recv() (*Packet, error)
	grpc.ClientStream
}

type dataCenterDownloadClient struct {
	grpc.ClientStream
}

func (x *dataCenterDownloadClient) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataCenterClient) Upload(ctx context.Context, opts ...grpc.CallOption) (DataCenter_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataCenter_serviceDesc.Streams[1], "/trace.DataCenter/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataCenterUploadClient{stream}
	return x, nil
}

type DataCenter_UploadClient interface {
	Send(*Packet) error
	CloseAndRecv() (*UploadResult, error)
	grpc.ClientStream
}

type dataCenterUploadClient struct {
	grpc.ClientStream
}

func (x *dataCenterUploadClient) Send(m *Packet) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataCenterUploadClient) CloseAndRecv() (*UploadResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataCenterClient) ShoutOut(ctx context.Context, opts ...grpc.CallOption) (DataCenter_ShoutOutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataCenter_serviceDesc.Streams[2], "/trace.DataCenter/ShoutOut", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataCenterShoutOutClient{stream}
	return x, nil
}

type DataCenter_ShoutOutClient interface {
	Send(*Judgment) error
	Recv() (*Judgment, error)
	grpc.ClientStream
}

type dataCenterShoutOutClient struct {
	grpc.ClientStream
}

func (x *dataCenterShoutOutClient) Send(m *Judgment) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataCenterShoutOutClient) Recv() (*Judgment, error) {
	m := new(Judgment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataCenterServer is the server API for DataCenter service.
type DataCenterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	Download(*empty.Empty, DataCenter_DownloadServer) error
	Upload(DataCenter_UploadServer) error
	ShoutOut(DataCenter_ShoutOutServer) error
}

// UnimplementedDataCenterServer can be embedded to have forward compatible implementations.
type UnimplementedDataCenterServer struct {
}

func (*UnimplementedDataCenterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedDataCenterServer) Download(req *empty.Empty, srv DataCenter_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (*UnimplementedDataCenterServer) Upload(srv DataCenter_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (*UnimplementedDataCenterServer) ShoutOut(srv DataCenter_ShoutOutServer) error {
	return status.Errorf(codes.Unimplemented, "method ShoutOut not implemented")
}

func RegisterDataCenterServer(s *grpc.Server, srv DataCenterServer) {
	s.RegisterService(&_DataCenter_serviceDesc, srv)
}

func _DataCenter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCenterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trace.DataCenter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCenterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCenter_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataCenterServer).Download(m, &dataCenterDownloadServer{stream})
}

type DataCenter_DownloadServer interface {
	Send(*Packet) error
	grpc.ServerStream
}

type dataCenterDownloadServer struct {
	grpc.ServerStream
}

func (x *dataCenterDownloadServer) Send(m *Packet) error {
	return x.ServerStream.SendMsg(m)
}

func _DataCenter_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataCenterServer).Upload(&dataCenterUploadServer{stream})
}

type DataCenter_UploadServer interface {
	SendAndClose(*UploadResult) error
	Recv() (*Packet, error)
	grpc.ServerStream
}

type dataCenterUploadServer struct {
	grpc.ServerStream
}

func (x *dataCenterUploadServer) SendAndClose(m *UploadResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataCenterUploadServer) Recv() (*Packet, error) {
	m := new(Packet)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DataCenter_ShoutOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataCenterServer).ShoutOut(&dataCenterShoutOutServer{stream})
}

type DataCenter_ShoutOutServer interface {
	Send(*Judgment) error
	Recv() (*Judgment, error)
	grpc.ServerStream
}

type dataCenterShoutOutServer struct {
	grpc.ServerStream
}

func (x *dataCenterShoutOutServer) Send(m *Judgment) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataCenterShoutOutServer) Recv() (*Judgment, error) {
	m := new(Judgment)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DataCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trace.DataCenter",
	HandlerType: (*DataCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _DataCenter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _DataCenter_Download_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _DataCenter_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ShoutOut",
			Handler:       _DataCenter_ShoutOut_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/center.proto",
}
